var frases = [
  'Enquanto a vida há esperança',
  'O futuro não é criado pelo que queremos, mas sim pelo que fazemos',
  'O seu senso de destino deve estar tão claro que você não precisa explicar para quem entra no barco com você.',
  'Não se preocupe com coisas que provavelmente não vão acontecer',
  "Ganhar dinheiro não é algo ruim, todos querem ganhar dinheiro e dois questionamentos acompanham esse desejo e eles são: Quanto é o suficiente? e O que você faz com esse dinheiro?",
  "Eu gosto do impossível, porque lá a concorrência é menor. - Walt Disney",
  "A preocupação do dinheiro deve existir até a questão de subsistência, após isso você deve se preocupar em como ser feliz o que você vai fazer com o dinheiro para ser feliz, como vai atingir os seus objetivos vitais e não monetários.",
  "Antes de consumir como um rico, produza como rico e para produzir como rico o segredo é o conhecimento e no know-how que é o conhecimento tácito.",
  "media as palavras que você usa, elas tem poder o que você fala reflete nos resultados que você obtêm.",
  "Escute as pessoas certas, escute apenas aquelas que foram colocadas por Jesus na sua vida para te ajudar, aquelas que você souber que não foram enviadas por ele não escute e corte o assunto.",
  "Se você se mostra frouxo no dia da angustia a tua força será pequena.",
  "O primeiro processo da transformação é identificação, o que você é?, o que precisa mudar?",
  "Controlar primeira a própria vida, para assim pode controlar a vida de uma empresa e das pessoas que trabalham nela.",
  "Deus não está preparando uma benção para você ele está te preparando para receber a benção.",
  "Deus me deu Deus tomou, seja louvado o nome do Senhor.",
  "Pedir um milagre é a forma mais covarde de fugir de um processo... A gente foca tanto no processo que esquece dos anos de governo que estão por vir, o casulo tem um tempo para acabar, mas o tempo de voo dura enquanto Deus quiser. Processo tem dia, data e hora para acabar, o governo que Deus te entrega após o processo não tem.",
  "Temam a Deus sobre todas as coisas, ame todas as pessoas elas são difíceis de mais de lidar, mas não tem nenhum outro caminho para felicidade aqui na terra ao não ser lidar com elas e por fim, para sua vida ficar mais leve você precisa ter duas coisas, a vida emocional em ordem e bons amigos ao lado.",
  "Códigos 1) Deus não chama quem está parado, ele usa até os despreparados mas não os desocupados. 2) tenha coragem essa é a única coisa que Deus não vai te dar, então você tem que correr atrás 3) Guarda o seu coração acima de tudo, onde estão os teus tesouros está o seu coração, então tome cuidado com o que se forma o seu tesouro, Deus vê o seu coração os homens veem sua preparação, então cuide do seu coração e depois da preparação.",
  "Aprenda a perdoar quem tentou te atrapalhar, a verdadeira felicidade vem de dentro para fora",
  "Emoções são passageiras decisões são permanentes, se você não está organizado por dentro tudo por fora vai estar desorganização, tudo é puro para o puro e tudo impuro para o impuro, a pessoa vê o mundo conforme ela está por dentro",
  "Nada que vem de fora pode quebrar a verdadeira felicidade",
  "Para ser feliz realmente nunca pare de doar aquilo que você tem (dom, dinheiro, tempo, networking) a felicidade está em compartilhar",
  "O futuro não é criado pelo que queremos ele é criado pelo que fazemos.",
  "Para construir o futuro precisa partir desses pontos, para onde eu vou?,  Você não consegue saber para onde vai se não sabe onde está,  senso de localização atual, senso de destino e mentores que pode ser por exemplo o GPS da sua vida.",
  "O seu senso de destino deve estar tão claro que você não precisa explicar para quem entra no barco com você.",
  "Não se preocupe com coisas que provavelmente não vão acontecer",
  "A única coisa que faz uma pessoa se libertar daquilo que lhe prende é o conhecimento",
  "O que é alma?, alma são suas emoções, os seus sentimentos e o seu intelecto, ou seja intelecto a forma como você pensa, as suas emoções como você lida com você mesmo e os seus sentimentos a forma como você lida com as pessoas.",
  "Quem compra o que não precisa logo terá que vender aquilo que precisa e porque as pessoa compram o que não precisam?, por aceitação!.",
  "Não deseje o que não é seu",
  "As frustações controlam como você gasta o seu dinheiro",
  "Construção da riqueza, Paz, família, conhecimento e vida espiritual,  dinheiro entra como recurso, com dinheiro você consegue desfrutar de uma forma diferente com a sua família, com dinheiro você consegue comprar mais livros e aumentar o seu conhecimento, com dinheiro eu consigo pagar minhas contas e facilitar a minha paz, dinheiro é um recurso dinheiro é a ferramenta da construção da riqueza",
  "Decida o que você quer, quanto mais você estiver alinhado com a meta e propósito da sua vida, menos você trabalha e mais você ganha.",
  "Se você não tiver planejamento na sua vida você nunca vai prosperar, Ah eu quero ser rico, como você vai ser rico?, quando vai ser rico?, em que você vai ser rico?, com quem você vai ser rico?, porque você quer ser rico?",
  "Seja humilde se humilhe de baixo da minha poderosa mão e deixe a ansiedade de longe reconheça que eu já estou ajudando e protegendo você",
  "Para ser feliz 1) não posso andar nos conselhos dos ímpios, 2) Não fique no caminho dos pecadores, 3) Não sente na roda dos escarnecedores.",
  "Para ser feliz deve ouvir e obedecer a Deus",
  "Você é como uma árvore então esteja próximo ao espírito santo, seja lavado pela palavra sempre e renove a sua mente todos os dias para que você conheça a boa e perfeita palavra de Deus",
  "A árvore que tem folhas te dá sombra(descanso) e alimento, ou seja  você é como uma árvore então de descanso e alimento para as pessoas",
  "Árvore que dá sombra e da fruto atrai a verdadeira prosperidade",
  "O pouco que você sabe e muito para quem sabe nada",
  "O que não podemos, desdenhamos e dizemos que não queremos",
  "Sem fé não é possível agradar a Deus, fé são as coisas que se esperam e você ainda não vê, fé é saber e acreditar que aquilo que não aconteceu já deu certo",
  "Quando você experimenta o futuro com a fé você muda o seu presente com sabedoria",
  "Sabedoria = Orar( consultar a aquele que já sabe o seu futuro e do que você precisa), observar(aprender sem passar por aquilo),  Convivendo (ambientes tem o poder de formatar ideias para o futuro, quanto mais ambientes que semêam ideias positivas você estiver inserido, mais ativado com a fé você fica e mais sabedoria você vai adquirir, pague o preço de conviver com pessoas onde sua fé será ativada e sua sabedoria será adquirida",
  "A sabedoria não é transferida com imposição de mãos, mas sim com convivência",
  "A combinação de fé e sabedoria causa uma explosão na sua trajetória",
  "Deus coloca talentos na nossa vida, mas as habilidades dos talentos é a gente que desenvolve",
  "quem vive seu propósito colhe resultado, entra no fluxo da prosperidade",
  "Dons e pessoas fortalecem o seu destino",
  "pequenas conexões podem revelar grande destinos",
  "Deus trabalha com processo e não com mágica",
  "Aprenda a lidar com pessoas, porque geralmente a palavra que vai mudar a sua vida vai vir de uma",
  "Quem quebra princípios abre mão da promessa",
  "princípios são eternos sentimento são passageiros, então viva pelo princípio e não pelo que sente",
  "O melhor posicionamento que você pode tomar é sendo exemplo",
  "Sabedoria não vem com idade, mas sim com batalhas vencidas",
];
